Update to Rollbar 1.1.x
baibaratsky/yii2-rollbar pull request #8
Opened 2017-06-09 04:04 UTC by skjb

2017-06-09 07:06 UTC, baibaratsky requested changes

2017-06-09 07:06 UTC, baibaratsky commented on composer.json
> +            "url": "https://asset-packagist.org"
Why to use https://asset-packagist.org here?

2017-06-09 21:39 UTC, skjb commented on composer.json
> +            "url": "https://asset-packagist.org"
I wasn't able to do a `composer install` without it, I kept getting a dependency error, but it may not be necessary

2017-06-09 22:42 UTC, baibaratsky commented on composer.json
> +            "url": "https://asset-packagist.org"
I think that wasn’t because of the rollbar package. Please remove these lines and I’ll merge the PR.

2017-06-10 02:15 UTC, skjb commented on composer.json
> +            "url": "https://asset-packagist.org"
Done

2017-06-10 09:06 UTC, baibaratsky approved these changes

2017-06-10 09:07 UTC, merged

2018-01-21 09:15 UTC, Borales commented
@baibaratsky hi!

could you please make a release with this change?

2018-01-21 09:57 UTC, baibaratsky commented
Sorry for delay
https://github.com/baibaratsky/yii2-rollbar/releases/tag/v1.6.0

2018-01-21 09:58 UTC, Borales commented
@baibaratsky thanks!